# Generated by Django 5.1.3 on 2025-02-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Product Name', max_length=255)),
                ('image', models.ImageField(default='product_images/facecaps.png', upload_to='product_images/')),
                ('images', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='₦', max_length=10)),
                ('description', models.CharField(default='Per item', max_length=255)),
                ('product_description', models.TextField(default='Detailed product description goes here.')),
                ('types', models.JSONField(default=list)),
                ('colors', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='api.product')),
            ],
        ),
    ]
