# Generated by Django 5.1.3 on 2025-02-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
    ]
