# Generated by Django 5.1.3 on 2025-02-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_image_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='types',
        ),
        migrations.AddField(
            model_name='order',
            name='design_file',
            field=models.FileField(blank=True, help_text='User-uploaded design file (image/PDF)', null=True, upload_to='designs/'),
        ),
    ]
