# Generated by Django 5.1.3 on 2025-02-26 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_types_order_design_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Delivery address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='Delivery city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='Delivery state', max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Delivery postcode (optional)', max_length=20, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='api.order')),
            ],
        ),
    ]
