# Generated by Django 5.1.3 on 2025-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design_file',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='cart_designs/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='order_designs/'),
        ),
    ]
