# Generated by Django 5.1.3 on 2025-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cartitem_color_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='increment_step',
            field=models.IntegerField(default=1),
        ),
    ]
