# Generated by Django 5.1.3 on 2025-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_number_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
